import Head from "next/head";
import Link from "next/link";
import { Grid, Container, Box } from "@mui/material";
import { DashboardLayout } from "../components";
import Cookies from "universal-cookie";
import RegisterForm from "./register";
import { useEffect, useState } from "react";
import React from "react";
import api from "../api";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { auth } from "../firebase";

// const cookies = new Cookies();
// const authToken = cookies.get("token");
// if (authToken) {
//   firstName: cookies.get("firstName");
//   lastName: cookies.get("lastName");
// }

export default function Home() {
  if (typeof window !== "undefined") {
    // Perform localStorage action
    const token = localStorage.getItem("accessToken");
  }

  useEffect(() => {
    // Perform localStorage action
    const token = localStorage.getItem("accessToken");
    // if (!token) {
    //   return <RegisterForm />;
    // }
  }, []);
  const [displayEmail, setDisplayEmail] = useState("");
  const [displayName, setDisplayName] = useState("");
  const user = auth.currentUser;
  if (user !== null) {
    const displayName = user.displayName;
    const email = user.email;
    const photoURL = user.photoURL;
    const emailVerified = user.emailVerified;

    const uid = user.uid;
  } else {
    return <RegisterForm />;
  }

  // export function getUserAuth() {
  //   return (dispatch) => {
  //     auth.onAuthStateChanged(async (user) => {
  //       if (user) {
  //         dispatch(setUser(user));
  //       }
  //     });
  //   };
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        your login info is
        {user.displayName} {"   "} {user.email}
      </DashboardLayout>
    </>
  );

  Home.getLayout = (page) => {
    <DashboardLayout>{page}</DashboardLayout>;
  };
}
