import Head from "next/head";
import { Grid, Container, Box } from "@mui/material";
import { DashboardLayout } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>grntrnrsg</DashboardLayout>;
    </>
  );

  Home.getLayout = (page) => {
    <DashboardLayout>{page}</DashboardLayout>;
  };
}
